[package]
name = "capnez"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp_derive = { path = "./capnp_derive", version = "0.1.0" }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
