[package]
name = "capnez-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
capnpc.workspace = true
syn.workspace = true
quote.workspace = true

walkdir = "2.4"
tempfile = "3.8"
structopt = "0.3"